= Task Manager - Ein Praxisbeispiel

Dieses Projekt enthält eine simple Task Manager API. Aufgaben können erstellt, bearbeitet, als erledigt markiert und
gelöscht werden.

== Technologien & Anforderungen
Es werden folgende Technologien verwendet:

- Java 21
- Gradle 8.13
- Spring Boot 3.4.5
- H2
- Lombok

Auch hier gilt: Sobald `java` auf dem System zur Verfügung steht, kann das Projekt gebaut und ausgeführt werden.
Sogar unter Windows.

== Wie ausführen?
Am Einfachsten ist es, den vorhandenen https://docs.gradle.org/current/userguide/gradle_wrapper.html[Gradle Wrapper] zu nutzen.
Es kann zwischen zwei Profilen gewählt werden: `dev` und `prod` . Ersteres verwendet eine in-memory H2 Datenbank und letztere PostgreSQL.

[,bash]
.Anwendung mit Profil ausführen
----
# Mit Profil 'dev' ausführen
./gradlew bootRun --args='--spring.profiles.active=dev'

# Mit Profil 'prod'  ausführen
./gradlew bootRun --args='--spring.profiles.active=prod'
----

NOTE:  Wenn auf dem Rechner Gradle installiert sein sollte, kann auch einfach `gradle` genutzt werden. Wenn dieses einen Gradle Wrapper vorfindet, wird der Aufruf an diesen delegiert.


Danach stehen die REST Endpunkte unter `http://localhost:8080/api` zur Verfügung.

== PostgreSQL
Im Profil `prod` wird versucht auf eine lokale PostgreSQL zuzugreifen. Eine passende Instanz kann einfach via Docker
erzeugt werden:

[,bash]
.PostgreSQL Instanz lokal erzeugen, stoppen, starten und löschen
----
# Docker Container mit PostgreSQL lokal erzeugen
docker run -itd --name taskdb -p 5432:5432 -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=postgres -e POSTGRES_DB=taskdb postgres:17-alpine

## Docker Container stoppen
docker stop taskdb

## Docker Container wieder starten
docker start taskdb

## Docker Container löschen
docker stop taskdb && docker rm taskdb
----

Danach stehen die REST Endpunkte unter `http://localhost:8080/api` zur Verfügung.

== Beispiel Requests
Es gibt unter link:./src/main/http/tasks-api.http[src/main/http/tasks-api.http] eine Definition, die im IntelliJ
HTTP Client direkt ausgeführt werden kann. Entweder einzeln oder komplett.

Die Definition sollte auch dafür genutzt werden können, andere Clients - z.B. `curl`, https://hoppscotch.io[Hoppscotch] oder https://postman.com[Postman] - ebenfalls zu benutzen.

== Docker und Docker Compose
Das im Projekt enthaltene link:./Dockerfile[Dockerfile] kann dafür genutzt werden, die Anwendung in ein Docker-Image zu
verpacken.

Dafür kann folgender Befehl genutzt werden:

[,bash]
.Docker Image erstellen
----
docker build -t task-manager:latest .
----

Das "Tag" ist im obigen Beispiel `task-manager:latest`. Darüber kann dann die Anwendung via Docker ausgeführt werden:

[,bash]
.Docker Container aus Image erstellen und ausführen
----
docker run -it --rm -e SPRING_PROFILES_ACTIVE=dev task-manager:latest
----

Das `--rm` sorgt dafür, dass der Container nach dem Beenden (mittels Ctrl/Strg+C) wieder gelöscht wird. `-e` lässt uns
Umgebungsvariablen setzen. Und `SPRING_PROFILES_ACTIVE` dient dazu, die gewünschten Profile - hier `dev` - zu aktivieren.

Es gibt auch eine link:./docker-compose.yml[docker-compose.yml] im Repository. Diese illustriert, wie wir mehrere
Docker Container orchestrieren könnten. Im verfügbaren Beispiel wird ein aktuelles Docker Image erstellt, darauf ein
Container gebaut und mit den Umgebungsvariablen gestartet, die das Profile `prod` aktivieren und die korrekten Zugangsdaten
für die PostgreSQL setzen, die wir in einem weiteren Container erstellen.
Damit Daten nicht verloren gehen, wird das Docker Volume `postgres_data` erstellt und in den PostgreSQL Docker Container
unter `/var/lib/postgresql/data` gemounted. Damit überleben die Daten, auch wenn wir zum Beispiel ein Versionsupdate
durchführen würden.

Um Docker Compose zu nutzen, führe im Wurzelverzeichnis des Projekt einfach folgendes aus:

[,bash]
.Anwendung und PostgreSQL mittels Docker Compose starten
----
docker compose up
----

Wenn beides im Hintergund laufen soll, setze noch den Parameter ´-d`.

Ein `docker compose rm` löscht die Docker erzeugten Container. Das Docker Volume muss ggf. manuell gelöscht werden.

== Kubernetes
Im Verzeichnis link:./k8s[k8s] befinden sich außerdem Kubernetes (k8s) Descriptoren,

Diese sind so aufgebaut, dass sowohl PostgreSQL als auch der Service in einem Cluster zur Verfügung gestellt werden.
Für PostgreSQL werden _Secrets_ angelegt, die dafür verwendet werden, die PostgreSQL Instanz aufzusetzen als auch den Service so zu konfigurieren, dass er sich mit der Instanz verbinden kann.

Die Secrets wurden mit folgendem Befehl erzeugt:

[,bash]
.Beispiel zum Erzeugen von Secrets
----
kubectl create secret generic postgres-secret \
  --from-literal=postgres-user=postgres \
  --from-literal=postgres-password=postgres \
  --dry-run=client -o yaml > postgres-secret.yaml
----

Er gibt außerdem Skripte für link:deploy-to-minikube.bat[Windows] und für link:deploy-to-minikube.sh[richtige Betriebssysteme], um die Anwendung zu bauen, in ein Docker Image und dann ein lokales Kubernetes zu packen, welches mit https://minikube.sigs.k8s.io[Minikube] zur Verfügung gestellt wird.
