spring:
  datasource:
    url: jdbc:h2:mem:taskdb
    driverClassName: org.h2.Driver
    username: sa
    password: password

  jpa:
    defer-datasource-initialization: true
#    hibernate:
#      ddl-auto: create-drop

  h2:
    console:
      enabled: true
      path: /h2-console
  
  sql:
    init:
      mode: always
